### ISSUE TITLE
Nothing renders to screen - empty imba tag

### ISSUE THREAD

**Issue by andregoldstein** [haikyuu/imba-inertia-adapter#2]
Am having an issue where the `inertia-app-xyz` is rendering and the tag inside it, in my case, `home` is rendering but it is empty.

I'm also not entirely sure on the convention, should the `resolve` function inside `createInertiaApp` call just the file name without the `.imba` prefix?

Thanks! Below a screenshot of outputted HTML

<img width="725" alt="Screenshot 2022-08-05 at 16 08 19" src="https://user-images.githubusercontent.com/7061578/183095766-ab21869f-dda4-4d7c-9b1b-0ca555e9c68f.png">

This is my entry file in Imba which I'm compiling into the equivalent `.js` file and calling that from my HTML

```
import { createInertiaApp } from 'imba-inertia-adapter'

console.log "Hi from Imba, updated now again, yay and again :)"

createInertiaApp
	resolve: do(name) "{name}"
	setup: do({ el, App, props })
		console.log { el, App, props }
		imba.mount <{App} props=props>
```

```
# pages/home.imba
tag home-page
	<self>
		<h1> "Homepage"
		<p> "Testing here again"
```

Not sure if this is the expected way to handle it. Thanks!

**Comment by andregoldstein** [comment]
@haikyuu I've created a basic repo, hopefully you can manage to run it with the correct Ruby setup etc. I've made it as simple as possible to see where I'm going wrong in implementing the adapter

https://github.com/andregoldstein/rails-inertia-imba

**Comment by haikyuu** [comment]
Wasn't successful installing rails.
I guess you need to manually import pages in your pages folder.

**Comment by andregoldstein** [comment]
Thanks, yes have given this a go as per your repo https://github.com/haikyuu/perfect-stack/blob/main/src/app.imba

Still getting blank output as per

<img width="273" alt="Screenshot 2022-08-18 at 20 55 04" src="https://user-images.githubusercontent.com/7061578/185472535-0f36b96c-7601-4c7d-80ee-e67a0b97d237.png">

Will keep trying!

**Comment by andregoldstein** [comment]
So it seems I was rendering the name of the file and not the actual `tag-name` and that was why it wasn't outputting (you were right, I also needed to import the files)

```
render inertia: "home-page", props: { name: "World" }
```

not

```
render inertia: "home", props: { name: "World" }
```
